SELECT `nome da coluna`
FROM `nome da tabela`;

SELECT * FROM `NOME DO BANCO`.`NOME DA COLUNA`
WHERE `NOME COLUNA` IS NULL;

SELECT * FROM `NOME DO BANCO`.`NOME DA COLUNA`
WHERE `NOME COLUNA` BETWEEN 10 AND 21;

SELECT * FROM `NOME DO BANCO`.`NOME DA COLUNA`
WHERE `NOME COLUNA` > 20 ORDER BY `NOME COLUNA` ASC;  -- CRESCENTE --

SELECT * FROM `NOME DO BANCO`.`NOME DA COLUNA`
WHERE `NOME COLUNA` > 20 ORDER BY `NOME COLUNA` DESC; -- DECRESCENTE --

SELECT * FROM `NOME DO BANCO`.`NOME DA COLUNA`
ORDER BY `NOME COLUNA` ASC;

SELECT * FROM `NOME DO BANCO`.`NOME DA COLUNA`
ORDER BY `NOME COLUNA` DESC;

SELECT * FROM `NOME DO BANCO`.`NOME DA COLUNA`
WHERE `NOME COLUNA` LIKE 'C%';  -- PEGA TODOS QUE COMEÇAM COM C --

SELECT * FROM `NOME DO BANCO`.`NOME DA COLUNA`
WHERE `NOME COLUNA` LIKE '%SILVA%';  -- PEGA TODOS QUE TENHAM SILVA ANTES OU DEPOIS DE SILVA --

SELECT * FROM `NOME DO BANCO`.`NOME DA COLUNA`
WHERE `NOME COLUNA` LIKE '_A%';  -- PEGA TODOS QUE TENHAM A SEGUNDA LETRA COM A E 0 OU MAIS LETRAS APÓS --


