AWSTemplateFormatVersion: '2010-09-09'
Description: Infraestrutura Deployment
Resources:
  DeployBucket: 
    Type: AWS::S3::Bucket
  BackupBucket: 
    Type: AWS::S3::Bucket
Outputs:
  DeployBucketName:
    Value:  !Ref DeployBucket
    Description: Deploy da aplicação
    Export:
      Name:  !Sub ${AWS::StackName}-DeployBucketName
  BackupBucketName:
    Value:  !Ref BackupBucket
    Description: Bucket para fazer bkp de logs e de dados da aplicação
    Export:
      Name:  !Sub ${AWS::StackName}-BackupBucketName